"""
Quick Start: DCA Strategy Backtesting
======================================

This script provides a simple way to run both DCA strategies and compare them.
"""

print("🎯 DCA Strategy Backtesting - Quick Start")
print("=" * 70)
print()
print("📋 STEP-BY-STEP GUIDE")
print("=" * 70)
print()
print("Step 1: Download Historical Data")
print("-" * 70)
print("  Run: python download_dca_data.py")
print("  This downloads daily data for BTC, ETH, BNB, and TRX")
print("  Data range: 2023-01-01 to 2024-12-31")
print()
print("Step 2: Run Strategy Comparison")
print("-" * 70)
print("  Run: python compare_dca_strategies.py")
print("  This runs both strategies and generates a comparison report")
print()
print("Step 3: Review Results")
print("-" * 70)
print("  Results are saved to: backtest_results/dca_comparison_[timestamp].json")
print("  Console output shows detailed performance metrics")
print()
print("=" * 70)
print()
print("📚 WHAT YOU GET")
print("=" * 70)
print()
print("✅ Two fully implemented DCA strategies:")
print("   1. Monthly DCA with Rebalancing")
print("      - Systematic buying every month")
print("      - Smart capital rebalancing")
print("      - Disciplined profit taking")
print()
print("   2. Signal-Based DCA")
print("      - Opportunistic buying on signals")
print("      - 10-point scoring system")
print("      - Dynamic position sizing")
print()
print("✅ Multi-asset backtesting:")
print("   - BTC (50% allocation)")
print("   - ETH (25% allocation)")
print("   - BNB (15% allocation)")
print("   - TRX (10% allocation)")
print()
print("✅ Comprehensive reports:")
print("   - Portfolio-level performance")
print("   - Per-symbol breakdown")
print("   - Risk metrics")
print("   - Trading activity analysis")
print("   - Key insights and winner determination")
print()
print("=" * 70)
print()
print("🛠️  CUSTOMIZATION")
print("=" * 70)
print()
print("Edit compare_dca_strategies.py to change:")
print("  - Time period (start_date, end_date)")
print("  - Initial capital (initial_cash)")
print("  - Monthly contribution (monthly_contribution)")
print("  - Asset allocation ratios")
print()
print("Edit src/strategies/dca_strategies.py to change:")
print("  - Strategy parameters (thresholds, percentages, etc.)")
print("  - Buy/sell rules")
print("  - Signal scoring system")
print()
print("=" * 70)
print()
print("📖 DETAILED DOCUMENTATION")
print("=" * 70)
print("  See: DCA_STRATEGIES_GUIDE.md")
print("  Complete guide with:")
print("    - Full strategy specifications")
print("    - Usage examples")
print("    - Customization options")
print("    - Troubleshooting tips")
print()
print("=" * 70)
print()
print("🚀 READY TO START!")
print("=" * 70)
print()
print("  1. Ensure virtual environment is activated:")
print("     Windows: .venv\\Scripts\\activate")
print("     Linux/Mac: source .venv/bin/activate")
print()
print("  2. Run: python download_dca_data.py")
print()
print("  3. Run: python compare_dca_strategies.py")
print()
print("=" * 70)
